name: fashinshop
description: Fashion Shop application.
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  provider: ^3.0.0
  intl: ^0.15.8
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  toast: ^0.1.5
  image_picker: ^0.6.7+1
  animated_text_kit: ^2.2.0
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/logo.jpeg
    - images/facebook.png
    - images/apple.png
    - images/google.png
    - images/cats/accessories.png
    - images/cats/dress.png
    - images/cats/shoe.png
    - images/products/dress/dr1.jpeg
    - images/products/dress/dr2.jpeg
    - images/products/dress/dr3.jpeg
    - images/products/dress/dr4.jpeg
    - images/products/dress/dr5.jpeg
    - images/products/dress/dr7.jpeg
    - images/products/dress/dr8.jpeg
    - images/products/dress/dr9.jpeg
    - images/products/dress/dr10.jpeg
    - images/products/dress/dr11.jpeg
    - images/products/dress/dr12.jpeg
    - images/products/dress/dr13.jpeg
    - images/products/dress/dr14.jpeg
    - images/products/dress/dr15.jpeg
    - images/products/dress/dr16.jpeg
    - images/products/pants/pa1.jpeg
    - images/products/pants/pa2.jpeg
    - images/products/pants/pa3.jpeg
    - images/products/pants/pa4.jpg
    - images/products/pants/pa5.jpeg
    - images/products/pants/pa6.jpeg
    - images/products/pants/pa7.jpeg
    - images/products/pants/pa8.jpeg
    - images/products/pants/pa9.jpeg
    - images/products/sets/set1.jpeg
    - images/products/sets/set2.jpeg
    - images/products/sets/set3.jpeg
    - images/products/sets/set4.jpeg
    - images/products/sets/set5.jpeg
    - images/products/sets/set6.jpeg
    - images/products/sets/set7.jpeg
    - images/products/skirts/sk1.jpeg
    - images/products/skirts/sk3.jpeg
    - images/products/skirts/sk4.jpeg
    - images/products/skirts/sk5.jpeg
    - images/products/skirts/sk6.jpeg
    - images/products/tops/tops1.jpeg
    - images/products/tops/tops2.jpeg
    - images/products/tops/tops3.jpeg
    - images/products/tops/tops4.jpeg
    - images/products/tops/tops5.jpeg
    - images/products/tops/tops6.jpeg
    - images/products/tops/tops7.jpeg
    - images/products/tops/tops8.jpeg
    - images/products/tops/tops9.jpeg
    - images/products/tops/tops10.jpeg
    - images/products/tops/tops11.jpeg
    - images/products/tops/tops12.jpeg
    - images/products/tops/tops13.jpeg
    - images/products/tops/tops14.jpeg
    - images/products/tops/tops15.jpeg
    - images/products/tops/tops16.jpeg
    - images/products/shoes/sh1.jpeg
    - images/products/shoes/sh2.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

